name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - name: github context
      run: echo '${{ toJSON(github) }}'
    - name: check githubcontext 
      run: |
        echo ${{ github.repository }}
        echo ${{ github.event_name }}