name: multiple-evnet-workflow
on:
  push:
  issues:
    types: [opened]
  workflow_dispatch:
    
jobs: 
    multiple-evnet-workflow-job:
        runs-on: ubuntu-latest
        steps: 
        - name : step1
          run : echo hello world
        - name : step2
          run : |
            echo hello world world 
            echo github action